version: '3'
services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/usr/src/app
    command: sh -c 'cd todo-react && yarn start'
    ports:
      - 3001:3001
    tty: true